### ISSUE TITLE
[BUG] Trying to place +1 Poison Damage Dia Sword in Anvil crashes game client

### ISSUE THREAD

**Issue by Chris92de** [red2blue/AQM2#168] opened 2022-03-09 23:28 UTC
**Modpack Version**
AQM2 v2.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Game client crashes when placing a +1 Poison Damage Diamon Sword into a regular anvil

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Have sword shown in screenshot below, place into any of the anvil slots -> Client crashes

**Expected behavior**
What is the expected outcome?
Client does not crash

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5523125/157556436-f13a902b-3b7b-428f-84a2-4358dca9d733.png)

**Crash log or latest.log.log**
[latest.log](https://pastebin.com/ynLq314A)

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment] 2022-03-11 00:05
duplicate of #169

**Closed as completed by itsdinkd** 2022-03-11 00:05 UTC
Labels: bug
