### ISSUE TITLE
[BUG] Bewitchment page not loading (updated and still an issue) 

### ISSUE THREAD

**Issue by Ray-YY** [red2blue/AQM2#208] opened 2022-04-10 08:58 UTC
Hello, I'm using another quality mod pack 2 version 2.1.2 and for some reason our bewitching book isn't loading 
![image](https://user-images.githubusercontent.com/76828060/162610710-5467109f-3f55-46b5-800b-9989e49d5aac.png)
This is the image we get when opening it, not sure what I can do. Please help! Cheers!

**Comment by itsdinkd** [comment] 2022-04-20 04:05
Duplicate of #149 
I suggest updating your modpack and restoring any kubejs changes made

**Closed as completed by itsdinkd** 2022-04-20 04:05 UTC
Labels: bug
