### ISSUE TITLE
Spectrum Trees not rendering properly.[BUG]

### ISSUE THREAD

**Issue by Dres-Tiefling** [red2blue/AQM2#204] opened 2022-04-05 16:06 UTC
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The dyed trees from the spectrum mod do not render in properly. They remain saplings until interacted with, then show one block at a time as you click connected blocks. Rubber saplings also do this. Because you need to break the spectrum tree blocks by hand to get the pure dyes it is extremely hard to collect from invisible trees. Bonemealing trees produces the same results as growing naturally.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash? Plant spectrum trees, allow to grow naturally or using bonemeal.

**Expected behavior**
What is the expected outcome?
Trees to be visually present on growth.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
No shaders or outside texture packs used. Optifine installed. Can confirm rubber tree issue is still present without optifine, assuming same for spectrum trees. On discord searching AQM2 support shows others having same issue with at least rubber trees, but never addressed.

**Comment by itsdinkd** [comment] 2022-04-06 08:22
I recommend asking in the spectrum discord

**Comment by itsdinkd** [comment] 2022-04-20 04:04
Also duplicate of #91

**Closed as completed by itsdinkd** 2022-04-20 04:04 UTC
Labels: bug
