### ISSUE TITLE
[BUG] Crash at startup

### ISSUE THREAD

**Issue by danilopez99** [red2blue/AQM2#194] opened 2022-03-24 02:25 UTC
**Modpack Version**
AQM2-2.1.2

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Minecraft does not start.

**Steps to reproduce the behavior:**
Instal openjdk 17
Install the modpack using multimc on linux and start the game.

**Expected behavior**
Crash at startup

**Screenshots**
.

**Crash log or latest.log.log**
https://pastebin.com/BcGi6mYw

**Additional context**
.

**Comment by Shadowner83** [comment] 2022-03-24 11:49
Is the attached log file the file from /home/tro/.local/share/multimc/instances/Another Quality Modpack 2 - 1.18.1/minecraft/hs_err_pid54524.log ?

I hardly see any direct reasons for the crash in your pastebin.

Can you try to install the modpack without MultiMC?

Just copy the server files to a new folder and then launch serverstart.sh

It should then automatically install itself.

**Comment by joeyleesi** [comment] 2022-03-24 18:38
I am having a similar issue with PolyMC. I tried running the startserver script as recommended which worked with no issues. 

Here are the two relevant logs from trying with PolyMC:
[MC Log](https://mclo.gs/N3ybx18)
[JVM Log](https://0x0.st/oNn0.txt)

I haven't found any other modpacks that cause this issue. For example, Another Quality Modpack 3 works no problem

**Comment by joeyleesi** [comment] 2022-03-24 18:55
Seems to be a duplicate of issue #29 
Following [these instructions](https://github.com/itsdinkd/AQM2/issues/29#issuecomment-1004491126) resolved the issue

**Closed as completed** 2022-03-29 23:25 UTC
Labels: bug
